theme:
    name: bootstrap
site_name: Samsonov Alexadnder

nav:
  - Home: index.md
  - Lab 1:
      - Task 1: ./Lab_1/task_1.md
      - Task 2: ./Lab_1/task_2.md
      - Task 3: ./Lab_1/task_3.md
      - Task 4: ./Lab_1/task_4.md
      - Task 5: ./Lab_1/task_5.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
